learning_rate:
  type: loguniform
  low: 1.0e-4
  high: 5.0e-3
embedding_dim:
  type: categorical
  choices: [16, 32, 64]
dnn_hidden_units:
  type: categorical
  choices:
    - [512, 256, 128]
    - [1024, 512, 256]
attention_type:
  type: categorical
  choices: [bilinear_attention, dot_attention]
attention_hidden_units:
  type: categorical
  choices:
    - [80, 40]
    - [64, 32]
net_dropout:
  type: uniform
  low: 0.0
  high: 0.5
batch_size:
  type: categorical
  choices: [2048, 4096, 8192]
